language: node_js
node_js:
- 0.1
sudo: required
notifications:
  email:
    recipients:
    - monitoring@respoke.io
before_install:
- openssl aes-256-cbc -K $encrypted_214cf3840981_key -iv $encrypted_214cf3840981_iv
  -in spec/config.json.enc -out spec/config.json -d
